package com.smc.svms.entity;

public enum ViolationType {
    UNAUTHORIZED_ZONE,
    TIME_RESTRICTION,
    LOCATION_VIOLATION,
    TIME_VIOLATION,
    OVERCROWDING,
    UNAUTHORIZED_VENDOR,
    HYGIENE_ISSUE,
    PRICE_COMPLAINT,
    BEHAVIOR_ISSUE,
    MISSING_LICENSE,
    EXPIRED_LICENSE,
    OTHER
}
